# Prometheus 配置文件 - 分布式任务调度系统监控

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 调度器 Dispatcher 监控
  - job_name: 'scheduler-dispatcher'
    static_configs:
      - targets: ['dispatcher:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # API 服务器监控
  - job_name: 'scheduler-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Worker 节点监控（如果 Worker 暴露指标端点）
  - job_name: 'scheduler-workers'
    static_configs:
      - targets: ['worker-1:8080', 'worker-2:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # PostgreSQL 监控（需要 postgres_exporter）
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    profiles:
      - database-monitoring

  # RabbitMQ 监控（需要 rabbitmq_exporter）
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 30s
    profiles:
      - queue-monitoring