# 认证配置示例

[api.auth]
# 启用认证
enabled = true

# JWT 密钥（生产环境中应该使用环境变量）
jwt_secret = "your-super-secret-jwt-key-at-least-32-characters-long"

# JWT 过期时间（小时）
jwt_expiration_hours = 24

# 需要认证的端点列表
require_auth_endpoints = [
    "/api/tasks",
    "/api/workers",
    "/api/system"
]

# API 密钥配置（哈希形式）
[api.auth.api_keys]

# 管理员密钥示例
[api.auth.api_keys."YWRtaW4ta2V5LWhhc2g="]
name = "admin-key"
permissions = ["Admin"]
is_active = true
created_at = "2024-01-01T00:00:00Z"

# 操作员密钥示例
[api.auth.api_keys."b3BlcmF0b3Ita2V5LWhhc2g="]
name = "operator-key"
permissions = ["TaskRead", "TaskWrite", "WorkerRead", "SystemRead"]
is_active = true
created_at = "2024-01-01T00:00:00Z"

# 只读用户密钥示例
[api.auth.api_keys."dmlld2VyLWtleS1oYXNo"]
name = "viewer-key"
permissions = ["TaskRead", "WorkerRead", "SystemRead"]
is_active = true
created_at = "2024-01-01T00:00:00Z"

# 完整的API配置示例
[api]
enabled = true
bind_address = "0.0.0.0:8080"
cors_enabled = true
cors_origins = ["*"]
request_timeout_seconds = 30
max_request_size_mb = 10