# 开发环境配置文件
# 继承 base.toml 的默认配置，只覆盖开发环境特定的设置

[database]
# 开发环境数据库连接
url = "postgresql://postgres:123456@localhost:5432/scheduler"

[message_queue]
# Redis Stream 开发环境配置
type = "redis_stream"
url = "redis://localhost:6379"

[worker]
# 开发环境 Worker 配置
worker_id = "dev-worker-001"
hostname = "localhost"
ip_address = "127.0.0.1"

[api]
# 开发环境 API 配置
bind_address = "127.0.0.1:8080"
cors_origins = ["http://localhost:3000", "http://localhost:8080", "http://127.0.0.1:3000", "http://127.0.0.1:8080"]

[api.auth]
# 开发环境认证配置（默认关闭）
jwt_secret = "dev_secret_key_for_development_only"

[observability]
# 开发环境日志级别
log_level = "debug"
jaeger_endpoint = "http://localhost:14268/api/traces"