# 生产环境配置文件
# 继承 base.toml 的默认配置，只覆盖生产环境特定的设置

[database]
# 生产环境数据库连接
url = "postgresql://db-host:5432/scheduler_prod"
max_connections = 50
min_connections = 10
connection_timeout_seconds = 60
idle_timeout_seconds = 1800

[message_queue]
# Redis Stream 生产环境配置
url = "redis://redis-host:6379"
max_retries = 5
retry_delay_seconds = 120
connection_timeout_seconds = 60

[message_queue.redis]
host = "redis-host"
connection_timeout_seconds = 60
max_retry_attempts = 5
retry_delay_seconds = 2

[dispatcher]
# 生产环境调度器配置
schedule_interval_seconds = 30
max_concurrent_dispatches = 500
worker_timeout_seconds = 180
dispatch_strategy = "load_balancer"

[worker]
# 生产环境 Worker 配置
worker_id = "prod-worker"
hostname = "worker-host"
ip_address = "10.0.0.100"
max_concurrent_tasks = 20
supported_task_types = ["shell", "http", "python"]
heartbeat_interval_seconds = 60
task_poll_interval_seconds = 10

[api]
# 生产环境 API 配置
bind_address = "0.0.0.0:8443"
cors_enabled = false
cors_origins = []
request_timeout_seconds = 60
max_request_size_mb = 50

[api.auth]
# 生产环境认证配置（启用）
enabled = true
jwt_secret = "placeholder_for_secret_manager"
jwt_expiration_hours = 8

[api.rate_limiting]
# 生产环境限流配置（启用）
enabled = true
max_requests_per_minute = 30
refill_rate_per_second = 0.5
burst_size = 5

[observability]
# 生产环境日志级别
log_level = "warn"
jaeger_endpoint = "http://jaeger:14268/api/traces"