# Security Configuration Template
# This template provides security-focused settings
# Copy to config/security.toml and customize as needed

# Encryption and secrets management
[secrets]
encryption_enabled = true
encryption_key_path = "/etc/ssl/encryption.key"
secret_manager_enabled = true
secret_rotation_enabled = true
secret_rotation_interval_days = 30
secret_history_retention_count = 5

# JWT security settings
[jwt]
algorithm = "HS256"
minimum_key_length = 64
expiration_hours = 8
refresh_expiration_hours = 24
issuer = "scheduler-system"
audience = "scheduler-api"
enable_refresh_tokens = true
refresh_token_expiration_days = 7

# API security settings
[api_security]
enable_request_signing = true
enable_response_validation = true
enable_input_sanitization = true
enable_output_sanitization = true
max_request_size_bytes = 52428800  # 50MB
max_response_size_bytes = 104857600  # 100MB
enable_rate_limiting = true
enable_ip_whitelisting = false
enable_ip_blacklisting = true

# CORS security settings
[cors_security]
enabled = false  # Disabled by default for security
allowed_origins = []
allowed_methods = ["GET", "POST", "PUT", "DELETE", "PATCH"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]
exposed_headers = []
allow_credentials = false
max_age_seconds = 3600

# TLS/SSL security settings
[tls_security]
enabled = true
minimum_version = "1.3"
cipher_suites = [
    "TLS_AES_256_GCM_SHA384",
    "TLS_AES_128_GCM_SHA256",
    "TLS_CHACHA20_POLY1305_SHA256"
]
enable_certificate_pinning = false
enable_hsts = true
hsts_max_age_seconds = 31536000  # 1 year
hsts_include_subdomains = true
hsts_preload = true

# Database security settings
[database_security]
enable_ssl = true
ssl_mode = "require"
enable_connection_pooling = true
max_pool_size = 50
min_pool_size = 10
connection_timeout_seconds = 60
enable_query_timeout = true
query_timeout_seconds = 300
enable_idle_connection_timeout = true
idle_connection_timeout_seconds = 1800

# Message queue security settings
[mq_security]
enable_ssl = true
enable_authentication = true
enable_authorization = true
enable_message_encryption = true
enable_queue_access_control = true
enable_message_signing = true

# Audit logging settings
[audit_logging]
enabled = true
log_security_events = true
log_auth_events = true
log_data_access = true
log_admin_actions = true
retention_days = 730
enable_real_time_alerts = true
enable_log_aggregation = true
enable_log_analysis = true

# Network security settings
[network_security]
enable_firewall = true
enable_ddos_protection = true
enable_rate_limiting = true
enable_ip_reputation = true
enable_geolocation_blocking = false
enable_bot_detection = true
max_connections_per_ip = 100
max_requests_per_ip_per_minute = 60

# File system security settings
[filesystem_security]
config_file_permissions = "600"
log_file_permissions = "640"
backup_file_permissions = "600"
enable_file_integrity_monitoring = true
enable_file_access_logging = true
sensitive_file_patterns = [
    "*.key",
    "*.pem",
    "*.crt",
    "*.p12",
    "*.pfx",
    "passwords*",
    "secrets*",
    "credentials*"
]

# Environment security settings
[environment_security]
development_mode = false
debug_mode = false
test_mode = false
enable_environment_validation = true
required_environment_variables = [
    "JWT_SECRET",
    "DB_PASSWORD",
    "REDIS_PASSWORD",
    "ENCRYPTION_KEY"
]
forbidden_environment_variables = [
    "DEBUG_PASSWORD",
    "TEST_SECRET",
    "DEFAULT_KEY"
]

# Monitoring and alerting security settings
[monitoring_security]
enable_security_monitoring = true
enable_anomaly_detection = true
enable_intrusion_detection = true
enable_vulnerability_scanning = true
enable_compliance_monitoring = true
alert_on_security_events = true
alert_on_policy_violations = true
alert_on_suspicious_activity = true

# Backup and recovery security settings
[backup_security]
enable_encrypted_backups = true
enable_backup_signing = true
enable_backup_integrity_verification = true
backup_retention_days = 90
enable_offsite_backups = true
enable_backup_access_control = true
enable_backup_audit_logging = true