# Scheduler Timeout Configuration Example
#
# This shows how to configure timeout values for different operation types
# in the distributed task scheduler system.

[timeout]
# Database operation timeouts (seconds)
database_timeout = 30
database_long_running_timeout = 300  # For migrations, bulk operations

# Message queue operation timeouts (seconds) 
message_queue_timeout = 10
message_queue_connection_timeout = 15

# External service call timeouts (seconds)
external_api_timeout = 15
webhook_timeout = 20

# Internal service communication timeouts (seconds)
internal_service_timeout = 5
inter_service_timeout = 8

# Task execution timeouts (seconds)
task_execution_default_timeout = 60
task_execution_max_timeout = 3600

# Scheduler operation timeouts (seconds)
schedule_scan_timeout = 45
dependency_check_timeout = 20
task_dispatch_timeout = 15

# Worker operation timeouts (seconds)
worker_heartbeat_timeout = 10
worker_registration_timeout = 15

# Circuit breaker timeout settings (seconds)
circuit_breaker_reset_timeout = 60

[timeout.environment]
# Environment-specific timeout overrides
[timeout.environment.development]
database_timeout = 60  # More generous timeouts for development
message_queue_timeout = 30

[timeout.environment.production]
database_timeout = 15  # Stricter timeouts for production
message_queue_timeout = 5

[timeout.environment.testing]
database_timeout = 5   # Fast timeouts for testing
message_queue_timeout = 2